### ISSUE TITLE
Bug: Commit hook always fails

### ISSUE THREAD

**Issue by apepper** [ssp/gitx#10]
With 97f2e2cd346c661b0fc4895d007136fb5e3151c5 I always get the following screen, when I try to commit:

<img width="538" alt="commit hook failed" src="https://cloud.githubusercontent.com/assets/86275/17582192/90e20e96-5faa-11e6-950e-a116317dba2b.png">

I do not have any commit hooks configured. With a previous version a890f7e2cd13b36a0301c44022808685bd43a3c9 all is good and the screen is not shown.

**Comment by larsblumberg** [comment]
I can confirm that

**Comment by apepper** [comment]
The diff between a working version and the no longer working version: https://github.com/ssp/gitx/compare/a890f7e...97f2e2c

**Comment by ssp** [comment]
@apepper @larsblumberg:
I am afraid I cannot reproduce this issue on my machine (running OS X 10.11.6, using GitX on the gitx repository).

Are you seeing the issue in a similar setup? If not: can you describe how to reproduce this?

Thanks!
