### ISSUE TITLE
Could you please upload a binary

### ISSUE THREAD

**Issue by yene** [ssp/gitx#12]
thx!

**Comment by davidswelt** [comment]
+1

**Comment by jakirkham** [comment]
Yeah, it seems like you have the most lively fork at this point. Would be great to at least have a git tag to recommend where one can build from.

**Comment by corysimmons** [comment]
It'd be really nice to figure out how to automate binary creation on a commit step.

**Comment by nanotech** [comment]
[Here's a build I made][0] from the [latest master commit][1]. The auto updater is still using the original configuration, so disable it and either watch this repository or subscribe to this issue for updates instead. I have not extensively tested this build, so, as always, please keep backups of your data.

[0]: https://github.com/nanotech/gitx/releases/tag/release-98f685f
[1]: https://github.com/ssp/gitx/commit/98f685f00f1c08e46fae12289964dda7e7225822

**Comment by corysimmons** [comment]
I was gonna release my latest build too, but I logged into it before creating the release, and wasn't sure if it was stashing my login somewhere so chickened out. :^)

**Comment by corysimmons** [comment]
@nanotech Your build doesn't work.

**Comment by yene** [comment]
I could it not get to work either, still using 2010 version. So depressing that 5 talented people can not untangle this messy but great product/code.

**Comment by nanotech** [comment]
@corysimmons @yene That build got compiled with an OpenSSL that assumed AVX2 is available. Try the new [`GitX-98f685f-2.zip`][0] build, which uses Homebrew's bottled OpenSSL and should run on more processors.

[0]: https://github.com/nanotech/gitx/releases/download/release-98f685f/GitX-98f685f-2.zip

**Comment by claytonrcarter** [comment]
This one appears to work.  Thanks!

**Comment by tambovchanin** [comment]
@nanotech Thank you

**Comment by yene** [comment]
@nanotech you are a hero
