### ISSUE TITLE
command line tool gitx only opens GitX in the background

### ISSUE THREAD

**Issue by apepper** [ssp/gitx#4]
When executing `gitx` in the terminal GitX is loaded with the current repository - but only on the background.

Previous versions of `gitx` started GitX in the foreground.

It would be great if GitX is opened in the foreground again. Also it seems that that executing `gitx` is quite slow (it currently needs ~5 seconds).

### Background information

* Build GitX from source (version 8ccc5e35e6ba7be96c9be3d553287bc2fdafdfdd). `gitx` is `/usr/local/bin/gitx` which symlinks to `/Applications/GitX.app/Contents/Resources/gitx`.
* OSX Version is 10.11.5 (15F34).
* XCode version 7.3 (7D175).
* Called `gitx` from `bash` and from `zsh`.

**Comment by ssp** [comment]
@apepper: I am not familiar with this aspect of the app, but I think I found a solution for the issue with the missing activation

I am not sure about the speed issue you mention. It may be unrelated.

**Comment by apepper** [comment]
@ssp Great. With a890f7e2cd13b36a0301c44022808685bd43a3c9 the command line tool is working again as intended. Thank you!
