### ISSUE TITLE
Plans for binary release?

### ISSUE THREAD

**Issue by rafaelgaspar** [ssp/gitx#5]
Do you have any plans on releasing binaries of your GitX fork? or just the code?

It would be nice to have binaries for download here with github releases.

**Comment by ssp** [comment]
Hey @rafaelgaspar,

I agree it would be »nice« to have a convenient current pre-built version of GitX but I’d rather not create yet another personal fork of the application that will die off soon.

Unfortunately there’s no agreement on how to team up and create a community fork at this point in time, so we’ll have to do with building for ourselves.
