### ISSUE TITLE
Push command doesn't find git-lfs tool

### ISSUE THREAD

**Issue by larsblumberg** [ssp/gitx#9]
I'm using git-lfs extension and I can run `git push` from the terminal successfully but when doing a push from within GitX I get this error message:

> Pushing feature/google-cast-integration to origin encountered an error.
> 
> command: git push origin feature/google-cast-integration
> 
> Warning: remote port forwarding failed for listen port 52698
> 
> This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
> 
> error: failed to push some refs to 'git@github.com:getSenic/nuimo-app-ios.git'
> 
> error = 1

Unlike the error message states, `git-lfs` is definitely on the search path.

Why doesn't GitX find `git-lfs`?

**Comment by ssp** [comment]
@larsblumberg 

I have no real idea about this (not using git-lfs myself).

My guess would be that the error message is correct but that a Cocoa application GitX does not have the same PATH as your shell does. If you have installed git-lfs via homebrew, you probably added /usr/local/bin to your $PATH in your .bashrc or .zshrc. Using the commit hook git-lfs installs itself

```
╰─ cat .git/hooks/pre-push
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.\n"; exit 2; }
git lfs pre-push "$@"
```
suggests that it depends on the git-lfs command being on your PATH.


Things you could try:

* launch GitX from the command line (it may keep the shell’s environment then)
* change the commit hook to reference /usr/local/bin/git-lfs (which will probably break things for collaborators not using homebrew)
* add /usr/local/bin to your PATH for Cocoa-applications (the old environment.plist way of doing that seems to be gone in current OS X versions)

**Comment by ssp** [comment]
@larsblumberg 

I don’t see how I can reasonably change anything on GitX’s side for this, so I’ll close this Issue now.

**Comment by larsblumberg** [comment]
@ssp: Thanks a lot for your help! I'll use good old command line for pushing for now.
